### ISSUE TITLE
md5 sum missmatch after runing .launch files

### ISSUE THREAD

**Issue by BaKristof** [Hacks4ROS/h4r_ev3_ctrl#22]
Maybe its useless ti ask for help here but i give it a try 
So anyway my problem is that after i ssh to my ev3 and strat the ev3_manager and then i launch a launch file from my PC i get md5sum mismatch on my ev3 and its disconnected for this
This is what i get on my ev3 :
root@Targonca:~# ev3_manager
Port: in4
Mode: angle
Publish rate: 10
getFilePTR opening: /sys/class/lego-sensor/sensor0/driver_name 0x597a0
str:lego-ev3-gyro
Str No: 0:lego-ev3-color
Str No: 1:lego-ev3-gyro<---
Driver Name: 3
[ERROR] [1455389241.402820121]: client wants service /Targonca/controller_manager/switch_controller to have md5sum b29a7abc673b2c54c14b54e50f8d06a5, but it has 5e857dedf71d6f337975e15a1e7cfdd8. Dropping connection.
[ERROR] [1455389241.504548829]: client wants service /Targonca/controller_manager/switch_controller to have md5sum b29a7abc673b2c54c14b54e50f8d06a5, but it has 5e857dedf71d6f337975e15a1e7cfdd8. Dropping connection.

and this is what i get on my PC:
kristof@kristof-MS-7D22:~/catkin_ws$ roslaunch h4r_ev3_launch gyro.launch ev3_hostname:=Targonca
... logging to /home/kristof/.ros/log/1926c4a8-79a3-11ee-8e54-39cccc692a25/roslaunch-kristof-MS-7D22-35470.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://kristof-MS-7D22:35493/

SUMMARY
========

PARAMETERS
 * /Targonca/Ev3Gyro/frame_id: gyro_link
 * /Targonca/Ev3Gyro/mode: angle
 * /Targonca/Ev3Gyro/port: in4
 * /Targonca/Ev3Gyro/publish_rate: 10
 * /Targonca/Ev3Gyro/topic_name: /gyro
 * /Targonca/Ev3Gyro/type: h4r_ev3_control/E...
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /Targonca/
    ev3_sensor_spawner (controller_manager/spawner)

ROS_MASTER_URI=http://localhost:11311

process[Targonca/ev3_sensor_spawner-1]: started with pid [35484]
[INFO] [1698946449.975530]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1698946449.982464]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1698946449.990141]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1698946449.997544]: Loading controller: Ev3Gyro
[INFO] [1698946454.222610]: Controller Spawner: Loaded controllers: Ev3Gyro
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 509, in call
    transport.connect(dest_addr, dest_port, service_uri)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 569, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 664, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 607, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: client wants service /Targonca/controller_manager/switch_controller to have md5sum b29a7abc673b2c54c14b54e50f8d06a5, but it has 5e857dedf71d6f337975e15a1e7cfdd8. Dropping connection.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/controller_manager/spawner", line 219, in <module>
    if __name__ == '__main__': main()
  File "/opt/ros/noetic/lib/controller_manager/spawner", line 211, in main
    resp = switch_controller(loaded, [], 2, False, 0.0)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 512, in call
    raise ServiceException("unable to connect to service: %s"%e)
rospy.service.ServiceException: unable to connect to service: remote error reported: client wants service /Targonca/controller_manager/switch_controller to have md5sum b29a7abc673b2c54c14b54e50f8d06a5, but it has 5e857dedf71d6f337975e15a1e7cfdd8. Dropping connection.
[INFO] [1698946454.337269]: Shutting down spawner. Stopping and unloading controllers...
[INFO] [1698946454.338138]: Stopping all controllers...
[WARN] [1698946454.353906]: Controller Spawner error while taking down controllers: unable to connect to service: remote error reported: client wants service /Targonca/controller_manager/switch_controller to have md5sum b29a7abc673b2c54c14b54e50f8d06a5, but it has 5e857dedf71d6f337975e15a1e7cfdd8. Dropping connection.
[Targonca/ev3_sensor_spawner-1] process has died [pid 35484, exit code 1, cmd /opt/ros/noetic/lib/controller_manager/spawner Ev3Gyro __name:=ev3_sensor_spawner __log:=/home/kristof/.ros/log/1926c4a8-79a3-11ee-8e54-39cccc692a25/Targonca-ev3_sensor_spawner-1.log].
log file: /home/kristof/.ros/log/1926c4a8-79a3-11ee-8e54-39cccc692a25/Targonca-ev3_sensor_spawner-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
i don't know what is the problem my bet is on the ros version (using noetic ubuntu 20.04.06) but i'm not sure i hope you could help me or just say what version of ros should i use

**Comment by BaKristof** [comment]
I solved it. The ros version was the problem i changed to ros kinetic instead of ros noatic and now run successfully

**Comment by dhruvilmahidhariya** [comment]
Hey there, I wanted to ask if it even runs on ROS Noetic? I have ros noetic. I have already simulated my ev3pick and place robot using ROS Noetic and gazebo. Now I want to implement it by customising nodes with the help of Yokto h4r controller. Can I even do that? or does it only runs on ros Kinetic?
